// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: PTspj

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
/*
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_align(ui_Screen1,LV_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_start_pause = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_start_pause, &ui_img_elements_start_png);
lv_obj_set_width( ui_img_start_pause, 20);
lv_obj_set_height( ui_img_start_pause, 20);
lv_obj_add_flag( ui_img_start_pause, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_start_pause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_img_start_pause, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_reset = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_reset, &ui_img_elements_reset_png);
lv_obj_set_width( ui_img_reset, 20);
lv_obj_set_height( ui_img_reset, 20);
lv_obj_set_x( ui_img_reset, 0 );
lv_obj_set_y( ui_img_reset, 148 );
lv_obj_add_flag( ui_img_reset, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_reset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_img_reset, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_pause = lv_img_create(ui_Screen1);
lv_img_set_src(ui_img_pause, &ui_img_elements_pause_png);
lv_obj_set_width( ui_img_pause, LV_SIZE_CONTENT);  /// 7
lv_obj_set_height( ui_img_pause, LV_SIZE_CONTENT);   /// 9
lv_obj_set_x( ui_img_pause, 6 );
lv_obj_set_y( ui_img_pause, 6 );
lv_obj_add_flag( ui_img_pause, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_pause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
*/
ui_Screen1 = lv_tileview_create(lv_scr_act());
lv_obj_align(ui_Screen1, LV_ALIGN_TOP_RIGHT, 0, 0);
lv_obj_set_size(ui_Screen1, LV_PCT(100), LV_PCT(100));
lv_obj_remove_style(ui_Screen1, 0, LV_PART_SCROLLBAR);

lv_obj_t *tv1 = lv_tileview_add_tile(ui_Screen1, 0, 0, LV_DIR_VER);
lv_obj_t *tv2 = lv_tileview_add_tile(ui_Screen1, 0, 1, LV_DIR_VER);

lv_obj_t *frame1 = lv_obj_create(tv1);
lv_obj_set_size(frame1, LV_PCT(100), LV_PCT(100));
lv_obj_align(frame1,LV_ALIGN_CENTER,0,0);
lv_obj_clear_flag(frame1, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(frame1, lv_color_black(), 0);
lv_obj_set_style_border_width(frame1,0,0);

lv_obj_t *main_cout = lv_obj_create(tv2);
lv_obj_set_size(main_cout, LV_PCT(100), LV_PCT(100));
lv_obj_clear_flag(main_cout, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_border_width(main_cout, 0, 0);
lv_obj_set_style_bg_color(main_cout, lv_color_white(), 0);
}
